version: "3.8"

services:
  backend:
    build: ./server
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - PORT=5000
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: node-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - PORT=3000
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
